version: 2
jobs:
  "php 7.3":
    docker:
      - image: circleci/php:7.3-fpm-stretch
    steps:
      - checkout

      - run:
          name: Validate composer file
          command: composer validate

      - run:
          name: Install dependencies
          command: make vendor

      - run:
          name: Run Tests
          command: |
            make coverage-test

      - run:
          name: Enforce Code Standards
          command: make code-standards

      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash) -f output/clover.xml

      - store_test_results:
          path: output

      - store_artifacts:
          path: output

workflows:
  version: 2
  build:
    jobs:
      - "php 7.3"
